### ISSUE TITLE
Error while running sum.py

### ISSUE THREAD

**Issue by pto2k** [cognitivetech/ollama-ebook-summary#11]
I got this error for running sum.py on the summarize.txt in this repo. Attached output.
Did I miss something in setup? I didn't get the 'Update Config File _config.yaml' part in the setup guide. Isn't that file alrady in this repo?
```
D:\Repo\ollama-ebook-summary>python sum.py --txt -v summarize.txt
Traceback (most recent call last):
  File "D:\Repo\ollama-ebook-summary\sum.py", line 459, in <module>
    main()
  File "D:\Repo\ollama-ebook-summary\sum.py", line 453, in main
    process_text_input(input_file, config, api_base, model, prompt_alias,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Repo\ollama-ebook-summary\sum.py", line 324, in process_text_input
    write_csv_header(writer, model)
TypeError: write_csv_header() takes 1 positional argument but 2 were given
```

**Comment by cognitivetech** [comment]
I'll try to look at that today. should be an easy fix

**Comment by cognitivetech** [comment]
https://github.com/cognitivetech/ollama-ebook-summary/commit/4633025c2cc1b1444e5f6288306cfc5d6e0e4333

fixed.. I was passing model name to the csv, no longer needed.
