### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by reikairen** [cognitivetech/ollama-ebook-summary#6]
C:\Users\reikairen\Desktop\ollama-ebook-summary-main>python book2text.py "article.pdf"
Traceback (most recent call last):
  File "C:\Users\reikairen\Desktop\ollama-ebook-summary-main\book2text.py", line 12, in <module>
    from lib.chunking import process_csv  # Import process_csv from chunking.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reikairen\Desktop\ollama-ebook-summary-main\lib\chunking.py", line 6, in <module>
    csv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long

**Comment by cognitivetech** [comment]
thanks for reporting, reikairen. I'll look into this, should be an easy fix.

**Comment by cognitivetech** [comment]
https://github.com/cognitivetech/ollama-ebook-summary/commit/47c2d088d06074adeb7bfc9ceb9db7184a857323

I have improved error handling for this case. please advise.
