### ISSUE TITLE
Feature request: Add a verbose argument

### ISSUE THREAD

**Issue by rafjaf** [cognitivetech/ollama-ebook-summary#7]
Thank you very much for sharing your code.

Since running sum.py can be quite long, it would be nice if it had a -v or --verbose argument to print the progress of the summarization process.

**Comment by cognitivetech** [comment]
good point, rafjaf.

what I do to check the progress is visually compare input csv to output csv. I have the whole project open in vs code so its easy to switch between files and see what's happening.

I used to print each as its going to the terminal.. but that only tells you its still working , not really how much progress made.

I will think about a good solution for this.

**Comment by cognitivetech** [comment]
yup, there you go! pull changes and you should find that -v prints output to the terminal
